### ISSUE TITLE
Intermitent LSB issues

### ISSUE THREAD

**Issue by fgiasson** [nvdk/virtuoso-rpm-builder#2]
Hi,

When I am installing Virtuoso using the RPM on CentOS 7, I get different behaviors regarding Virtuoso's startup after the installation. About 50% of the time, after I installed Virtuoso, I am getting this error:

```
-- Unit virtuoso.service has begun starting up.
Nov 18 20:56:31 ip-10-33-195-229 virtuoso[21283]: Starting Virtuoso OpenSource Edition virtuoso-opensource[  OK  ]
Nov 18 20:56:31 ip-10-33-195-229 virtuoso[21283]: /etc/rc.d/init.d/virtuoso: line 175: log_progress_msg: command not found
Nov 18 20:56:31 ip-10-33-195-229 systemd[1]: virtuoso.service: control process exited, code=exited status=127
Nov 18 20:56:31 ip-10-33-195-229 systemd[1]: Failed to start LSB: Virtuoso OpenSource Edition.
-- Subject: Unit virtuoso.service has failed
```

I have no knowledge in LSB, so I don't see why sometimes `log_progress_msg` would be defined, and other times it won't.

Also, I am installing redhat-lsb prior to the Virtuoso installation like this:

```
yum install -y redhat-lsb
```

Thanks!

**Comment by nvdk** [comment]
Hey,

I've updated the package to use systemd, hopefully this will resolve your issue.
